### ISSUE TITLE
Nominatim Error On the latest image

### ISSUE THREAD

**Issue by muslimcodeid** [robjuz/helm-charts#24]
Hi

I tried to install nominatim on my kubernetes server using this chart
But i got this following error message when my pods initializing

2022-09-23 04:12:45: Using project directory: /nominatim
2022-09-23 04:12:45: Setting up website directory at /nominatim/website
Traceback (most recent call last):
  File "/usr/local/bin/nominatim", line 14, in <module>
    exit(cli.nominatim(module_dir='/usr/local/lib/nominatim/module',
  File "/usr/local/lib/nominatim/lib-python/nominatim/cli.py", line 264, in nominatim
    return parser.run(**kwargs)
  File "/usr/local/lib/nominatim/lib-python/nominatim/cli.py", line 126, in run
    return args.command.run(args)
  File "/usr/local/lib/nominatim/lib-python/nominatim/clicmd/refresh.py", line 146, in run
    self._get_tokenizer(args.config)
  File "/usr/local/lib/nominatim/lib-python/nominatim/clicmd/refresh.py", line 165, in _get_tokenizer
    self.tokenizer = tokenizer_factory.get_tokenizer_for_db(config)

In this case i am using custom values because i only need the nominatim UI because i have the nominatim DB on external server.
But it wont work on mediagis/nominatim:4.1 when i downgrade the image to 3.7,its work

Thanks in advance

**Comment by robjuz** [comment]
Hi
Could you please show me you values file?

It looks like a problem with the tokenizer. The 3.7 is using the legacy tokenizer. How have you imported the DB? Are you using the legacy tokenizer with the nominatim postgres module?

**Comment by muslimcodeid** [comment]
Hello Robjuz,

Thanks for your reply and sorry for late reply.
You can refer to value yaml file below :

https://pastebin.com/VL1iagjk

I try to re run this latest chart for nominatim and it seems still get same error message like what i said before

2023-01-18 05:52:49: Setting up website directory at /nominatim/website
Traceback (most recent call last):
  File "/usr/local/bin/nominatim", line 14, in <module>
    exit(cli.nominatim(module_dir='/usr/local/lib/nominatim/module',
  File "/usr/local/lib/nominatim/lib-python/nominatim/cli.py", line 264, in nominatim
    return parser.run(**kwargs)
  File "/usr/local/lib/nominatim/lib-python/nominatim/cli.py", line 126, in run
    return args.command.run(args)
  File "/usr/local/lib/nominatim/lib-python/nominatim/clicmd/refresh.py", line 162, in run
    self._get_tokenizer(args.config)
  File "/usr/local/lib/nominatim/lib-python/nominatim/clicmd/refresh.py", line 181, in _get_tokenizer
    self.tokenizer = tokenizer_factory.get_tokenizer_for_db(config)
  File "/usr/local/lib/nominatim/lib-python/nominatim/tokenizer/factory.py", line 98, in get_tokenizer_for_db
    tokenizer.init_from_project(config)
  File "/usr/local/lib/nominatim/lib-python/nominatim/tokenizer/legacy_tokenizer.py", line 134, in init_from_project
    _install_module(config.DATABASE_MODULE_PATH,
  File "/usr/local/lib/nominatim/lib-python/nominatim/tokenizer/legacy_tokenizer.py", line 67, in _install_module
    shutil.copy(str(src_dir / 'nominatim.so'), str(destfile))
  File "/usr/lib/python3.10/shutil.py", line 417, in copy
    copyfile(src, dst, follow_symlinks=follow_symlinks)
  File "/usr/lib/python3.10/shutil.py", line 254, in copyfile
    with open(src, 'rb') as fsrc:
FileNotFoundError: [Errno 2] No such file or directory: '/usr/local/lib/nominatim/module/nominatim.so'

fyi again,that i am using externaldatabase,so it means that my kubernetes server and nominatim database in separate server also i am not make any customize config specially for tokenizer

Please Advice

Thanks in advance

**Comment by robjuz** [comment]
I will try to take another look on it during the weekend.

**Comment by muslimcodeid** [comment]
Alright, Thank you @robjuz
